#!/bin/bash

set -e

echo "=== Manual Deployment Steps for Cold Backend v1.3 ==="
echo ""
echo "Run these commands one by one:"
echo ""
echo "# 1. Build Go binary"
echo "go build -o server cmd/server/main.go"
echo ""
echo "# 2. Build Docker image (you may need to log out and back in for docker group to take effect)"
echo "docker build -t cold-backend:v1.3 ."
echo ""
echo "# 3. Save Docker image"
echo "docker save cold-backend:v1.3 > cold-backend-v1.3.tar"
echo ""
echo "# 4-8. Copy and import to all K3s nodes"
echo "for NODE_IP in 192.168.15.110 192.168.15.111 192.168.15.112 192.168.15.113 192.168.15.114; do"
echo "    scp cold-backend-v1.3.tar lakshya@\$NODE_IP:/tmp/"
echo "    ssh lakshya@\$NODE_IP 'sudo k3s ctr images import /tmp/cold-backend-v1.3.tar && rm /tmp/cold-backend-v1.3.tar'"
echo "done"
echo ""
echo "# 9. Update deployment files"
echo "sed -i 's/cold-backend:v1.2/cold-backend:v1.3/g' k8s/03-deployment-employee.yaml"
echo "sed -i 's/cold-backend:v1.2/cold-backend:v1.3/g' k8s/04-deployment-customer.yaml"
echo ""
echo "# 10. Apply deployments"
echo "ssh lakshya@192.168.15.110 'kubectl apply -f /home/lakshya/jupyter-/cold/cold-backend/k8s/03-deployment-employee.yaml'"
echo "ssh lakshya@192.168.15.110 'kubectl apply -f /home/lakshya/jupyter-/cold/cold-backend/k8s/04-deployment-customer.yaml'"
echo ""
echo "# 11. Check rollout status"
echo "ssh lakshya@192.168.15.110 'kubectl rollout status deployment/cold-backend-employee'"
echo "ssh lakshya@192.168.15.110 'kubectl rollout status deployment/cold-backend-customer'"
echo ""
echo "# 12. Verify pods"
echo "ssh lakshya@192.168.15.110 'kubectl get pods -l app=cold-backend -o wide'"
echo ""
echo "=== After deployment, access: ==="
echo "Monitoring Dashboard: http://192.168.15.110:30090"
